### ISSUE TITLE
less变量覆盖的正确姿势

### ISSUE THREAD

**Issue by lovelope** [lovelope/blog#6]
# less变量覆盖测试

## a.less 文件
```less
/* filename: a.less */
@primary: green;
@secondary: blue;

.section {
  @color: @primary;

  .element {
    color: @color;
  }
}
```

## 1. 尝试直接覆盖 `@color` 无效，结果仍和`@primary`一致
```bash
lessc a.less a.css --modify-var='@color=pink'
```
结果如下：
```css
.section .element {
  color: green;
}
```

## 2. 尝试覆盖 `@primary` 生效，结果和覆盖的变量一致
```bash
lessc a.less a.css --modify-var='@primary=yellow'
```
结果如下：
```css
.section .element {
  color: yellow;
}
```

## 结果
**覆盖 less 变量需要覆盖原始变量**
